In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
iris = pd.read_csv('data/iris.csv')
iris = iris.drop(iris.columns[[0]],axis=1)
iris.head()

In [ ]:
mappings = {
  'setosa': 0,
  'versicolor': 1,
  'virginica': 2
 }
iris['Species'] = iris['Species'].apply(lambda x: mappings[x])
iris.head()

In [ ]:
X = iris.drop('Species', axis=1).values
y = iris['Species'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

In [ ]:
class ANN(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(in_features=4, out_features=16)
        self.fc2 = nn.Linear(in_features=16, out_features=12)
        self.output = nn.Linear(in_features=12, out_features=3)
  
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.output(x)
        return x

In [ ]:
model = ANN()
model

In [ ]:
loss = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

In [ ]:
epochs = 100
loss_arr = []
for i in range(epochs):
    y_hat = model.forward(X_train)
    loss = loss(y_hat, y_train)
    loss_arr.append(loss)

    if i % 10 == 0:
        print(f'Epoch: {i} Loss: {loss}')

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [ ]:
preds = []
with torch.no_grad():
    for val in X_test:
        y_hat = model.forward(val)
        preds.append(y_hat.argmax().item())

In [ ]:
df = pd.DataFrame({'Y': y_test, 'YHat': preds})
df['Correct'] = [1 if corr == pred else 0 for corr, pred in zip(df['Y'], df['YHat'])]

In [3]:
import scipy.io as scio
import numpy as np

mem_n = 30;
key = 'mt'
key1 = key+'_x'
dataFile = '../data/data.mat'
data = scio.loadmat(dataFile)
data.keys()

data_x = data[key+'_x']
data_y = data[key+'_y']

L = len(data_x)

data_x_temp = np.pad(data_x,((0, mem_n), (0, 0)), 'wrap').T

data_x_new = np.zeros([L,mem_n])
for i in range(L):
    data_x_new[i,:] = data_x_temp[:,i:mem_n+i]
    




C:\Users\kevin\AppData\Local\Temp\ipykernel_9932\1698386021.py:20: ComplexWarning: Casting complex values to real discards the imaginary part
  data_x_new[i,:] = data_x_temp[:,i:mem_n+i]


In [6]:
aaa = data_x_new[:,0]

In [38]:
import numpy as np
a = np.arange(100).reshape(100,1)
n = 12
b = np.pad(a,((0, n), (0, 0)), 'wrap').T
c = np.zeros([100,12])
for i in range(100):
    c[i,:] = b[:,i:n+i]
    print(c[i,:])


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
[ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
[ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
[ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22.]
[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]
[13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24.]
[14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25.]
[15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26.]
[16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.]
[17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]
[18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
[19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]


In [47]:
a = np.arange(10)
b = np.arange(10)
c = a + b*1j
c[2]

(2+2j)