In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

df = pd.read_table('training.data', sep = ' ', names = ['x1', 'x2', "x3", "x4", "x5", "x6", "y"])
xx = df.iloc[:,:3].values
for i in range(20):
    print(xx[i])
a, b = xx[0][0], xx[0][1]
print(a, b)

[0.65307 0.9135  0.99926]
[0.95969 2.0065  3.3661 ]
[0.9135  0.99926 1.362  ]
[2.0065 3.3661 2.8797]
[0.99926 1.362   1.5848 ]
[3.3661 2.8797 2.8833]
[1.362  1.5848 1.4066]
[2.8797 2.8833 1.7312]
[1.5848 1.4066 1.5855]
[2.8833  1.7312  0.96023]
[1.4066 1.5855 1.6136]
[1.7312  0.96023 2.5968 ]
[1.5855 1.6136 1.5779]
[0.96023 2.5968  1.3746 ]
[1.6136 1.5779 1.8405]
[2.5968  1.3746  0.73455]
[1.5779 1.8405 1.4832]
[1.3746  0.73455 1.7031 ]
[1.8405 1.4832 1.0927]
[0.73455 1.7031  2.6156 ]
0.65307 0.9135
